---
apiVersion: v1
kind: Pod
metadata:
  name: memleak
  labels:
    app: memleak
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: target-node
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 0
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 0
  containers:
    - name: memleak
      image: ghcr.io/matti/docker-memleak:latest
